project:
  type: website
  output-dir: docs
  
website: 
  title: "Junyi Zhou Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Basic Information
      - href: edu.qmd
        text: Academic Performance
      - href: ResearchExperience.qmd
        text: Research Experience
      - href: InternExperience.qmd
        text: Intern Experience
      - href: PersonalSkills.qmd
        text: Personal Skills
format: 
  html: 
    theme: cosmo
    toc: true
